### ISSUE TITLE
Inquiry about experimental data

### ISSUE THREAD

**Issue by sherlockhomes1** [LZH-YS1998/STHSL#1]
Dear author, this is a great project, the results are as figures, but I don't understand it very well, how to tune the parameters to get the results in the article。
![X0M CUXM9HU%C4L ZV74H%K](https://github.com/LZH-YS1998/STHSL/assets/143397506/5c9ef7e7-ad81-444e-ae56-7743a60e57b3)

**Comment by LZH-YS1998** [comment]
Thank you for your interest in this work. The crime categories in this study are represented by numbers 0 to 3, where 0 corresponds to Burglary, 1 corresponds to Larceny, 2 corresponds to Robbery, and 3 corresponds to Assault. The reported results in the paper on NYC dataset are as follows: 
```
MAE_0=0.7329, MAPE_0=0.4788, MAE_1=1.0316, MAPE_1=0.5040, MAE_2=0.7912, MAPE_2=0.4595, MAE_3=0.8484, MAPE_3=0.5029.
```
The result is similar to the results you showed. It is possible that the variations in the experimental results can be attributed to factors such as the version of PyTorch, CUDA, and the GPUs or other hardware used. However, the differences between different configurations were not significantly pronounced.
